modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="alchemical"
version="1.0.0"
displayName="Alchemical"
displayURL="https://mcreator.net"
credits="Made by Vuserr"
authors="Vuserr"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.alchemical]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alchemical]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration